export const ERRORS = {
    USER_NOTFOUND: 'VIIXET_AUTHN_USER_NOTFOUND',
    USER_ALREADYEXISTS: 'VIIXET_AUTHN_USER_ALREADYEXISTS',
    CREDENTIALS_INVALID: 'VIIXET_AUTHN_CREDENTIALS_INVALID',
    SESSION_EXPIRED: 'VIIXET_AUTHN_SESSION_EXPIRED',
    SESSION_NOTFOUND: 'VIIXET_AUTHN_SESSION_NOTFOUND',
    TOKEN_NOTFOUND: 'VIIXET_AUTHN_TOKEN_NOTFOUND',
    TOKEN_INVALID: 'VIIXET_AUTHN_TOKEN_INVALID'
}